// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUk8K4RvQsgnQs0yYXOs6IqkcrRCy8J2Y',
    appId: '1:620042636782:web:16067b1829f741c0e052ff',
    messagingSenderId: '620042636782',
    projectId: 'vitel-global',
    authDomain: 'vitel-global.firebaseapp.com',
    storageBucket: 'vitel-global.appspot.com',
    measurementId: 'G-VYD2Y8K9SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5aBPaclR5WducZyIyF0D_lxmK7aFAEc',
    appId: '1:318352650622:android:e25169c0aecf7f6177032f',
    messagingSenderId: '',
    projectId: 'neox-ucm',
    storageBucket: 'neox-ucm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AaVCWXo8jyFek84TIC0Oh6vtODIZBpU',
    appId: '1:620042636782:ios:d7472d262e0a5880e052ff',
    messagingSenderId: '620042636782',
    projectId: 'vitel-global',
    storageBucket: 'vitel-global.appspot.com',
    iosClientId: '620042636782-kma0ro1e849lfv8idgltiaho2r4vr1t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1AaVCWXo8jyFek84TIC0Oh6vtODIZBpU',
    appId: '1:620042636782:ios:d7472d262e0a5880e052ff',
    messagingSenderId: '620042636782',
    projectId: 'vitel-global',
    storageBucket: 'vitel-global.appspot.com',
    iosClientId: '620042636782-kma0ro1e849lfv8idgltiaho2r4vr1t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
