name: neoxapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get:
  flutter_svg:
  device_info_plus:
  desktop_window: ^0.4.0


  flutter_udid:
  google_fonts:
#  flutter_screenutil:
  azlistview: ^2.0.0
  flutter_keyboard_visibility: ^6.0.0
  socket_io_client: ^2.0.1
  flutter_ringtone_player:
  shared_preferences:
  intl:
  lpinyin:
  tuple:
  flutter_foreground_task: ^6.1.2
  flutter_contacts: ^1.1.7+1
  flutter_local_notifications: ^16.2.0
  firebase_messaging: ^14.7.9
  fast_contacts: ^3.1.2
  flutter_audio_waveforms: ^1.2.1+8
  flutter_callkit_incoming: ^2.0.0+2
  contacts_service: ^0.6.3
  alphabet_list_scroll_view_fix: ^2.0.2
  flutter_slidable: ^0.6.0-nullsafety.0
  uuid: ^3.0.6
  firebase_core: ^2.24.2
  fluttertoast: ^8.2.4
  pinput: ^3.0.1
  dropdown_button2: ^2.3.9
#  janus_client:
  flutter_sms_inbox: ^1.0.3
  audio_waveforms: ^1.0.1
  image_picker: ^1.0.5
  photo_view: ^0.14.0
  auto_size_text_field: ^2.2.2
  shimmer: ^3.0.0
  appinio_video_player: ^1.2.2
  video_player: ^2.8.1
  #open_file: ^3.2.0
  just_audio: ^0.9.11
  audio_session: ^0.1.6
  path_provider: ^2.1.2
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  open_filex: ^4.3.4
  video_thumbnail: ^0.5.3
  record: ^4.4.4
  file_picker: ^6.1.1
  image_size_getter: ^2.1.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  responsive_framework: ^1.1.1
  window_manager: ^0.3.7
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
  audioplayers: ^5.2.1
#  flutter_native_splash: ^2.3.9
  auto_size_text: ^3.0.0
  get_storage: ^2.1.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  sqflite: ^2.3.0
  wakelock_plus: ^1.1.4
  top_snackbar_flutter:
  web_socket_client: ^0.1.0
  share_plus: ^7.2.1
  map_launcher: ^3.1.0
  url_launcher: ^6.2.4
  moment_dart: ^1.1.0
  back_button_interceptor: ^7.0.1
  encrypt: ^5.0.1
  jwt_decoder: ^2.0.1
  http: ^1.2.0
  flutter_audio_manager_plus:
    git:
      url: https://gitlab.com/kaushik512/flutter-contacts
      ref: flutter_audio_manager_plus_v1
  headset_connection_event: ^3.1.0
  sip_ua:
    path: ./sip_ua



dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/
    - assets/audio/
    - lib/presentation/screen/
    - lib/presentation/screen/login/
    - lib/presentation/screen/login/model/
    - lib/presentation/screen/login/mobile_email/
    - lib/presentation/screen/login/forgot_password/
    - lib/presentation/screen/login/auto_provisioning/
    - lib/presentation/screen/login/manual_provisioning/
    - lib/presentation/screen/caller/
    - lib/presentation/screen/caller/view/
    - lib/presentation/screen/detail/
    - lib/presentation/screen/splash/
    - lib/presentation/screen/calling/
    - lib/presentation/screen/desktop/
    - lib/presentation/screen/dialpad/
    - lib/presentation/screen/message/
    - lib/presentation/screen/message/view/
    - lib/presentation/screen/restore/
    - lib/presentation/screen/setting/
    - lib/presentation/screen/dashboard/
    - lib/presentation/screen/dashboard/model/
    - lib/presentation/screen/dashboard/dialer/
    - lib/presentation/screen/dashboard/contact/
    - lib/presentation/screen/dashboard/contact/view/
    - lib/presentation/screen/dashboard/history/
    - lib/presentation/screen/dashboard/history/view/
    - lib/presentation/screen/video_calls/
    - lib/presentation/screen/transfer_calls/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Heebo
     fonts:
        - asset: fonts/Heebo-Bold.ttf
        - asset: fonts/Heebo-ExtraBold.ttf
        - asset: fonts/Heebo-Light.ttf
          weight: 400
        - asset: fonts/Heebo-Medium.ttf
        - asset: fonts/Heebo-SemiBold.ttf
        - asset: fonts/Heebo-Regular.ttf
   - family: Lato
     fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Regular.ttf


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
